sudo: required
services:
    - docker
    
script:
        - docker build -t ysagron/node . 
        - docker images ysagron/node
before_deploy: 
    - docker login -u ysagron -p ys123456
    
deploy: 
    provider: script
    script: docker push ysagron/node

on:
    branch: master
